### ISSUE TITLE
Fails to install using the Quick Start guide

### ISSUE THREAD

**Issue by LunarJetman0** [littlstar/ls-psvr-encoder#13]
The quick start guide for MacOS no longer works.  Errors from logs below;

```
get-cursor-position@1.0.3 install /usr/local/lib/node_modules/ls-psvr-encoder/node_modules/get-cursor-position
> node-gyp rebuild

  CXX(target) Release/obj.target/pos/src/pos.o
../src/pos.cc:272:10: error: no matching member function for call to 'Set'
    pos->Set(String::NewFromUtf8(isolate, "row"), Number::New(isolate, row));
    ~~~~~^~~
/Users/davensangeelee/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3639:37: note: candidate function not
      viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/davensangeelee/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3642:37: note: candidate function not
      viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/pos.cc:273:10: error: no matching member function for call to 'Set'
    pos->Set(String::NewFromUtf8(isolate, "col"), Number::New(isolate, col));
    ~~~~~^~~
/Users/davensangeelee/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3639:37: note: candidate function not
      viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/davensangeelee/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3642:37: note: candidate function not
      viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/pos.cc:277:11: error: no template named 'Handle'
void Init(Handle<Object> exports) {
          ^
../src/pos.cc:280:59: error: too few arguments to function call, single argument 'context' was not specified
      FunctionTemplate::New(isolate, Method)->GetFunction());
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/davensangeelee/Library/Caches/node-gyp/14.3.0/include/node/v8.h:6404:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/davensangeelee/Library/Caches/node-gyp/14.3.0/include/node/v8config.h:422:31: note: expanded from macro
      'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
4 errors generated.
make: *** [Release/obj.target/pos/src/pos.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/usr/local/Cellar/node/14.3.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/ls-psvr-encoder/node_modules/get-cursor-position
gyp ERR! node -v v14.3.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! get-cursor-position@1.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the get-cursor-position@1.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/davensangeelee/.npm/_logs/2020-05-24T20_33_49_652Z-debug.log
```

**Comment by vipyne** [comment]
Hi @LunarJetman0, thanks for bringing this up.  It looks like you are using Node version 14.3.0, try to install using Node version 10.20.1 (worked on my MBP).

**Comment by neuralnetworkz** [comment]
since brew disabled node10 i used nvm and installed 10.24.1 on my MBP through that, thanks for the hint @vipyne
