### ISSUE TITLE
SyntaxError: unexpected token

### ISSUE THREAD

**Issue by renaudcerrato** [littlstar/ls-psvr-encoder#5]
doesn't work on my Linux ?

```
> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.04
Release:        17.04
Codename:       zesty

> node -v
v4.7.2

> lspe   
/usr/local/lib/node_modules/ls-psvr-encoder/node_modules/string-kit/lib/unicode.js:49
        return String.fromCodePoint( ... array ) ;
                                     ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ls-psvr-encoder/node_modules/string-kit/lib/string.js:54:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

```

**Comment by agrathwohl** [comment]
I believe your version of Node is too old. Can you upgrade to the current Node LTS version and try again?

**Comment by renaudcerrato** [comment]
I'm on Ubuntu 17.04, using nodejs from the repo. You should give some
instructions about the minimum version required:

https://nodejs.org/en/download/package-manager/

**Comment by renaudcerrato** [comment]
Using nodejs from the above repo just killed my nodejs install. npm rebuild doesn't solve it. I give up.

```
➜  lspe -i 1440P_6000K_142452572.mp4 -d 180 -t sbs 
module.js:664
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The module '/usr/local/lib/node_modules/ls-psvr-encoder/node_modules/get-cursor-position/build/Release/pos.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:664:18)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/ls-psvr-encoder/node_modules/get-cursor-position/index.js:1:74)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)

```

**Comment by agrathwohl** [comment]
You'll just need to start over again to fix that problem.

First, do:

`npm -r littlstar/ls-psvr-encoder -g`

Then do:

`npm install littlstar/ls-psvr-encoder -g`

That should fix it.

**Comment by agrathwohl** [comment]
Closing this issue for now. Please re-open it if re-installing from scratch does not solve your issue.
